Repository jupyterhub/action-major-minor-tag-calculator, pull requests merged in 2021-04, with the labels that each got.

#63 Update License from boilerplate entry to JupyterHub
  LICENSE
Labels: maintenance

#62 ci: add automation to update release branches on GitHub releases
  .github/workflows/release-updates.yml
Labels: ci

#64 Pre-release handling
  __tests__/main.test.js
  dist/index.js
  dist/index.js.map
  src/index.js
Labels: bug

#67 Add CHANGELOG.md for a v1.1.0 release
  CHANGELOG.md
Labels: documentation

#68 Documentation tweaks to action.yml / README.md pre-publishing
  README.md
  action.yml
Labels: documentation

#73 exclude invalid versions from existing tags
  dist/index.js
  dist/index.js.map
  src/index.js
Labels: bug

#74 Add changelog for v1.1.1
  CHANGELOG.md
Labels: documentation

#75 Set permissions.contents=write in workflows
  .github/workflows/release-updates.yml
  .github/workflows/test-and-update.yml
Labels: ci
