Repository jupyterhub/action-major-minor-tag-calculator, pull requests merged in 2023-11, with the labels that each got.

#323 Update all dependencies, move to Node 20
  .github/workflows/test-and-update.yml
  .github/workflows/test.yml
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package-lock.json
  package.json
Labels: dependencies, breaking

#326 Allow prefix to be a whitespace/comma separated list of prefixes
  README.md
  __tests__/main.test.js
  dist/index.js
  dist/index.js.map
  src/index.js
Labels: enhancement

#329 Default branchRegex input to a regex describing valid tags
  CHANGELOG.md
  action.yml
Labels: bug
